// <auto-generated />
using System;
using CMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Site.Core.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandColorEnd")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandColorStart")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorEnd")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorStart")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TransferId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Комфортный трансфер на Российскую строительную неделю 2026. Автобус.ру — надёжный перевозчик.",
                            IsDefault = false,
                            IsPublished = true,
                            Slug = "rsn-2026",
                            Title = "Трансфер на РСН 2026 — Автобус.ру",
                            TitlePage = "Трансфер на РСН 2026",
                            TransferId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Удобный трансфер на выставку Иннопром 2026 в Екатеринбурге.",
                            IsDefault = false,
                            IsPublished = true,
                            Slug = "innoprom-2026",
                            Title = "Трансфер на Иннопром 2026 — Avtobus.ru",
                            TitlePage = "Трансфер на Иннопром 2026",
                            TransferId = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BrandColorEnd = "#e55d00",
                            BrandColorStart = "#ff6b00",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Трансфер на международную выставку WorldFood Moscow 2026.",
                            IsDefault = false,
                            IsPublished = true,
                            Slug = "worldfood-2026",
                            Title = "Трансфер на WorldFood 2026 — Автобус.ру",
                            TitlePage = "Трансфер на WorldFood 2026",
                            TransferId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Site.Core.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandColorEnd")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandColorStart")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("INN")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OGRN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorEnd")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorStart")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Transfers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandColorEnd = "#c4171c",
                            BrandColorStart = "#e31e24",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "events.autobus.ru",
                            Email = "info@avtobus.ru",
                            INN = "7700000001",
                            LegalAddress = "г. Москва, ул. Примерная, д. 1",
                            Name = "Автобус.ру",
                            OGRN = "1027700000001",
                            Phone = "+7 (800) 555-35-35",
                            PrimaryColorEnd = "#e31e24",
                            PrimaryColorStart = "#e31e24",
                            Slug = "avtobusru",
                            TransportType = "Автобус",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BrandColorEnd = "#1557b0",
                            BrandColorStart = "#1a73e8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "events.avtobus1.ru",
                            Email = "info@avtobusru.com",
                            INN = "7700000002",
                            LegalAddress = "г. Москва, ул. Другая, д. 2",
                            Name = "Avtobus.ru",
                            OGRN = "1027700000002",
                            Phone = "+7 (800) 555-35-36",
                            PrimaryColorEnd = "#2d9249",
                            PrimaryColorStart = "#34a853",
                            Slug = "avtobusru-en",
                            TransportType = "Минивэн",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Site.Core.Models.Event", b =>
                {
                    b.HasOne("Site.Core.Models.Transfer", "Transfer")
                        .WithMany("Events")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("Site.Core.Models.Transfer", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
